# Web
server:
  port: 2017

spring:
  data:
    web:
      pageable:
        default-page-size: 100


  # H2 Database
  datasource:
    url: jdbc:h2:file:~/mylib/db/database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=YEAR,MONTH,USER
    username: sa
  jpa:
    hibernate:
      ddl-auto: update

# Thymeleaf
  thymeleaf:
    cache: false

# Authentication
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
